#!/bin/bash

urldecode() {
    local url_encoded="${1//+/ }"
    printf '%b' "${url_encoded//%/\\x}"
}

read -r url_encoded_input

url_encoded_input="${url_encoded_input#*=}"

input=$(urldecode "$url_encoded_input")

echo "$input" | ./lmcomp - "/tmp/$$.pdf"

echo "Content-type: application/pdf"
echo ""

cat "/tmp/$$.pdf"
rm "/tmp/$$.pdf"
